// =======================================
// 📦 Import Required Modules
// =======================================
const express = require("express");
const router = express.Router(); // 📌 Router instance helps keep routes modular instead of defining them in the main app file

const { authenticationToken } = require("../middleware/auth_middleware"); // 🔐 JWT authentication middleware
const asyncHandler = require("../utils/asyncHandler"); // 🔁 Handles async errors (removes try-catch)

// 🧠 Service layer that handles business logic for generating report data
const { exportTransactions } = require("../services/report.service");

/**
 * ======================================================
 * 📌 TAG: Report APIs
 * ======================================================
 */

/**
 * ======================================================
 * 📤 EXPORT TRANSACTIONS REPORT
 * ======================================================
 * @route   GET /api/report/export
 * @access  Private (JWT protected)
 *
 * Query Params (optional):
 * - startDate (YYYY-MM-DD)
 * - endDate (YYYY-MM-DD)
 * - categoryIds (comma-separated string)
 * - type ('Income' or 'Expense')
 * - minAmount
 * - maxAmount
 * - search
 *
 * Controller Responsibility:
 * - Extract query parameters
 * - Call service layer
 * - Send CSV file response
 *
 * Logical Flow:
 * 1️⃣ Authenticate user using JWT middleware
 * 2️⃣ Extract filters from query params
 * 3️⃣ Service fetches transactions and converts them to CSV
 * 4️⃣ Controller sends CSV file as downloadable attachment
 * Flow:
 * - Authenticate user via JWT middleware.
 * - Extract optional filter parameters from the request query.
 * - Generate a CSV string from filtered transactions via the report service.
 * - Set response headers to prompt a file download.
 * - Send the CSV data as the response body.
 */
/**
 * @swagger
 * /api/report/export:
 *   get:
 *     summary: Export transactions report (CSV)
 *     description: Download filtered transactions as CSV file
 *     tags: [Report]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: startDate
 *         schema:
 *           type: string
 *         description: Start date (YYYY-MM-DD)
 *       - in: query
 *         name: endDate
 *         schema:
 *           type: string
 *         description: End date (YYYY-MM-DD)
 *       - in: query
 *         name: categoryIds
 *         schema:
 *           type: string
 *         description: Comma-separated list of category IDs
 *       - in: query
 *         name: type
 *         schema:
 *           type: string
 *           enum: [Income, Expense]
 *         description: Filter by Income or Expense
 *       - in: query
 *         name: minAmount
 *         schema:
 *           type: number
 *         description: Minimum transaction amount
 *       - in: query
 *         name: maxAmou/nt
 *         schema:
 *           type: number
 *         description: Maximum transaction amount
 *       - in: query
 *         name: search
 *         schema:
 *           type: string
 *         description: Search keyword
 *     responses:
 *       200:
 *         description: CSV file downloaded successfully
 *         content:
 *           text/csv:
 *             schema:
 *               type: string
 */
router.get(
  "/export",
  authenticationToken,
  asyncHandler(async (req, res) => {
    // 🔑 userId comes from authentication middleware after decoding JWT
    // Logical reason: ensures report contains only that user's data
    const userId = req.userId;

    const csv = await exportTransactions(userId, {
      startDate: req.query.startDate,
      endDate: req.query.endDate,
      categoryIds: req.query.categoryIds,
      type: req.query.type,
      minAmount: req.query.minAmount,
      maxAmount: req.query.maxAmount,
      search: req.query.search,

      // Default sorting for export
      // Logical reason:
      // - Transactions usually viewed chronologically
      // - Latest transactions first
      sortBy: "t.trn_date",
      order: "DESC",
    });

    // Set response headers for CSV file download
    // Logical reason: informs browser that the response is a CSV file
    res.header("Content-Type", "text/csv");

    // Logical reason: forces browser to download file instead of displaying it
    res.attachment("transactions.csv");

    // Sends CSV string generated by service
    res.send(csv);
  }),
);

// =======================================
// 📤 Export Router
// =======================================
module.exports = router;
