// =======================================
// 📦 Import Required Modules
// =======================================
const express = require("express");
const router = express.Router(); // 📌 Router instance helps keep routes modular instead of defining them in the main app file

const { sendError } = require("../utils/responseHelper"); // 📤 Standard API response helpers

const { authenticationToken } = require("../middleware/auth_middleware"); // 🔐 JWT authentication middleware

// 🧠 Service layer that handles business logic for generating report data
const { exportTransactions } = require("../services/report.service");

/**
 * ======================================================
 * 📤 EXPORT TRANSACTIONS REPORT
 * ======================================================
 * @route   GET /report/export
 * @access  Private (JWT required)
 *
 * Controller Responsibility:
 * - Extract query parameters
 * - Call service layer
 * - Send CSV file response
 *
 * Logical Flow:
 * 1️⃣ Authenticate user using JWT middleware
 * 2️⃣ Extract filters from query params
 * 3️⃣ Service fetches transactions and converts them to CSV
 * 4️⃣ Controller sends CSV file as downloadable attachment
 */
router.get("/export", authenticationToken, async (req, res) => {
  // 🔑 userId comes from authentication middleware after decoding JWT
  // Logical reason: ensures report contains only that user's data
  const userId = req.userId;

  try {
    const csv = await exportTransactions(userId, {
      startDate: req.query.startDate,
      endDate: req.query.endDate,
      categoryIds: req.query.categoryIds,
      type: req.query.type,
      minAmount: req.query.minAmount,
      maxAmount: req.query.maxAmount,
      search: req.query.search,

      // Default sorting for export
      // Logical reason:
      // - Transactions usually viewed chronologically
      // - Latest transactions first
      sortBy: "t.trn_date",
      order: "DESC",
    });

    // Set response headers for CSV file download
    // Logical reason: informs browser that the response is a CSV file
    res.header("Content-Type", "text/csv");

    // Logical reason: forces browser to download file instead of displaying it
    res.attachment("transactions.csv");

    // Sends CSV string generated by service
    res.send(csv);
  } catch (err) {
    // Handles unexpected errors during report generation
    return sendError(res, {
      statusCode: 500,
      message: err.message,
    });
  }
});

// =======================================
// 📤 Export Router
// =======================================
module.exports = router;
